---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: gcr.io/istio-release
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: "/dev/stdout"
  components:
    cni:
      enabled: true
      namespace: kube-system
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          priorityClassName: system-cluster-critical
          hpaSpec:
            minReplicas: 3
            maxReplicas: 6
          replicaCount: 6
          resources:
            requests:
              cpu: 850m
              memory: 1024Mi
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                    matchLabels:
                      app: istio-ingressgateway
                - topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                    matchLabels:
                      app: istio-egressgateway
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          priorityClassName: system-cluster-critical
          hpaSpec:
            minReplicas: 3
            maxReplicas: 6
          replicaCount: 6
          resources:
            requests:
              cpu: 850m
              memory: 1024Mi
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                    matchLabels:
                      app: istio-ingressgateway
                - topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                    matchLabels:
                      app: istio-egressgateway
  values:
    global:
      imagePullPolicy: Always
      # defaultNodeSelector:
      #  role: istio-system
      # defaultTolerations:
      #   - key: "dedicated"
      #     operator: "Equal"
      #     value: "istio-system"
      #     effect: "NoSchedule"
    # gateways:
    #   istio-ingressgateway:
    #     serviceAnnotations:
    #       service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    #       service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    cni:
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
      excludeNamespaces:
       - istio-system
       - kube-system
       - cert-manager
      logLevel: info

